name: CD - Deploy to GCP (Manual)

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    name: Deploy Flask App to Cloud Run (GCP Cloud Build)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Submit build to Cloud Build
      run: |
        IMAGE=asia-south2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-repo/flask-api
        gcloud builds submit . --tag $IMAGE \
        --service-account=projects/${{ secrets.GCP_PROJECT_ID }}/serviceAccounts/${{ secrets.GCP_SA_EMAIL }} \
        --gcs-log-dir=gs://flask-files/build-logs/


    - name: Deploy to Cloud Run
      run: |
        IMAGE=asia-south2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-repo/flask-api
        gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
          --image $IMAGE \
          --platform managed \
          --region asia-south2 \
          --allow-unauthenticated
